/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Noor6VpK16b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "#app/components/ui/button"
import { DialogTrigger, DialogTitle, DialogHeader, DialogDescription, DialogFooter, DialogContent, Dialog } from "#app/components/ui/dialog"

export function StatsPopup({children, popupTitle, triggerTitle, elKey}: {children: React.ReactNode, popupTitle: string, triggerTitle: string, elKey?: string}) {
  return (  
    <Dialog key={elKey}>
      <DialogTrigger asChild>
        <Button variant="outline" className="text-foreground">{triggerTitle}</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px] lg:max-w-6xl w-full h-5/6 overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{popupTitle}</DialogTitle>
        </DialogHeader>
        
        {children}

      </DialogContent>
    </Dialog>
  )
}
