name: Seed and Update Database

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly at midnight on Sunday
  workflow_dispatch: # Allow manual triggering

jobs:
  seed-and-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run database seed
        run: npx prisma db seed

      - name: Export database to SQL
        run: sqlite3 prisma/dev.db .dump > dump.sql

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          /home/runner/.fly/bin/flyctl auth token $FLY_API_TOKEN
          /home/runner/.fly/bin/flyctl ssh console --command "sqlite3 /data/sqlite.db < /app/dump.sql"
