-- CreateTable
CREATE TABLE "Player" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "season" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "position" TEXT NOT NULL,
    "shoots" TEXT NOT NULL,
    "team" TEXT NOT NULL,
    "jersey" INTEGER NOT NULL,
    "gp" INTEGER NOT NULL,
    "goals" INTEGER NOT NULL,
    "assists" INTEGER NOT NULL,
    "actions" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Shift" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "detailCode" TEXT NOT NULL,
    "gameId" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "period" INTEGER NOT NULL,
    "startTime" DATETIME NOT NULL,
    "duration" INTEGER NOT NULL,
    "endTime" DATETIME NOT NULL,
    "shiftNumber" INTEGER NOT NULL,
    "typeCode" TEXT NOT NULL,
    "eventNumber" INTEGER NOT NULL,
    "eventDescription" TEXT NOT NULL,
    "playerId" INTEGER NOT NULL,
    CONSTRAINT "Shift_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Event" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "yrGm" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "maxRegulationPeriods" INTEGER NOT NULL DEFAULT 3,
    "number" INTEGER NOT NULL,
    "periodType" TEXT NOT NULL DEFAULT 'REG',
    "minutesElapsed" INTEGER NOT NULL,
    "secondsElapsed" INTEGER NOT NULL,
    "minutesRemaining" INTEGER NOT NULL,
    "secondsRemaining" INTEGER NOT NULL,
    "situationCode" TEXT NOT NULL,
    "homeTeamDefendingSide" TEXT NOT NULL,
    "typeCode" TEXT NOT NULL,
    "zero" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    "xCoord" REAL NOT NULL,
    "yCoord" REAL NOT NULL,
    "zoneCode" TEXT NOT NULL,
    "awayScore" INTEGER NOT NULL,
    "awaySOG" INTEGER NOT NULL,
    "homeScore" INTEGER NOT NULL,
    "homeSOG" INTEGER NOT NULL,
    "eventOwnerTeamId" TEXT NOT NULL,
    "shotType" TEXT NOT NULL,
    "playerId" INTEGER NOT NULL,
    "shootingPlayerId" INTEGER NOT NULL,
    "blockingPlayerId" INTEGER NOT NULL,
    "goalieInNetId" INTEGER NOT NULL,
    "winningPlayerId" INTEGER NOT NULL,
    "losingPlayerId" INTEGER NOT NULL,
    "committedByPlayerId" INTEGER NOT NULL,
    "drawnByPlayerId" INTEGER NOT NULL,
    "servedByPlayerId" INTEGER NOT NULL,
    "hittingPlayerId" INTEGER NOT NULL,
    "hitteePlayerId" INTEGER NOT NULL,
    "descKey" TEXT NOT NULL,
    "duration" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "secondaryReason" TEXT NOT NULL,
    "scoringPlayerId" INTEGER NOT NULL,
    "scoringPlayerTotal" INTEGER NOT NULL,
    "assist1PlayerId" INTEGER NOT NULL,
    "assist1PlayerTotal" INTEGER NOT NULL,
    "assist2PlayerId" INTEGER NOT NULL,
    "assist2PlayerTotal" INTEGER NOT NULL,
    CONSTRAINT "Event_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
