name: Seed Database

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - main
  # push:
  #   branches:
  #     - 'data/seed-*'

jobs:
  seed-database:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./seed.local.db

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Reset local database
        run: npx prisma migrate reset --skip-seed --force

      - name: Create prod-seed.local.js if it doesn't exist
        run: |
          if [ ! -f ./prod-seed.local.js ]; then
            cp ./prisma/seed.js ./prod-seed.local.js
            echo "Created prod-seed.local.js from prisma/seed.js"
          else
            echo "prod-seed.local.js already exists"
          fi

      - name: Run custom seed script
        run: node ./prod-seed.local.js

      - name: Create SQL dump
        run: sqlite3 ./seed.local.db .dump > seed.local.sql

      - name: Debug - Print first 20 lines of SQL dump
        run: head -n 20 seed.local.sql

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy seed to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          /home/runner/.fly/bin/flyctl auth token $FLY_API_TOKEN

          # Create a temporary script file to execute the SQL commands
          echo "sqlite3 /data/sqlite.db < /tmp/seed.local.sql" > /tmp/execute_seed.sh
          chmod +x /tmp/execute_seed.sh

          # Upload the SQL dump and the temporary script file
          /home/runner/.fly/bin/flyctl sftp shell <<EOF
          put seed.local.sql /tmp/seed.local.sql
          put /tmp/execute_seed.sh /tmp/execute_seed.sh
          bye
          EOF

          # Execute the temporary script file within the Fly.io environment
          /home/runner/.fly/bin/flyctl ssh console -C "sh /tmp/execute_seed.sh"

      # - name: Upload SQL dump as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: database-dump
      #     path: seed.local.sql
