name: Seed Database

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - 'data/seed-*' # Run on pushes to branches starting with data/seed-

  # Uncomment the following lines to enable scheduled runs
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday

jobs:
  seed-database:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run database seed
        run: npx prisma db seed

      - name: Export database to SQL
        run: sqlite3 $DATABASE_URL .dump > dump.sql

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          /home/runner/.fly/bin/flyctl auth token $FLY_API_TOKEN
          /home/runner/.fly/bin/flyctl ssh console --command "sqlite3 /data/sqlite.db < /app/dump.sql"

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update database after seeding" -a || echo "No changes to commit"
          git push
