name: Seed Database

on:
  workflow_dispatch:
  push:
    branches:
      - 'data/seed-*'

jobs:
  seed-database:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./seed.local.db

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Reset local database
        run: npx prisma migrate reset --skip-seed --force

      - name: Create prod-seed.local.ts if it doesn't exist
        run: |
          if [ ! -f ./prod-seed.local.ts ]; then
            cp ./prisma/seed.ts ./prod-seed.local.ts
            echo "Created prod-seed.local.ts from prisma/seed.ts"
          else
            echo "prod-seed.local.ts already exists"
          fi

      - name: Compile TypeScript
        run: npx tsc

      - name: Run custom seed script
        run: node ./prod-seed.local.js

      - name: Create SQL dump
        run: sqlite3 ./seed.local.db .dump > seed.local.sql

      - name: Debug - Print first 20 lines of SQL dump
        run: head -n 20 seed.local.sql

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy seed to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # /home/runner/.fly/bin/flyctl tokens create > flytoken.txt
          # FLYTOKEN=$(cat flytoken.txt)
          /home/runner/.fly/bin/flyctl auth token $FLY_API_TOKEN

          # Upload the SQL dump
          /home/runner/.fly/bin/flyctl sftp shell < ./upload_seed.sh

          # Apply the SQL dump
          /home/runner/.fly/bin/flyctl ssh console -C "sqlite3 /data/sqlite.db < /tmp/seed.local.sql"

      # - name: Upload SQL dump as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: database-dump
      #     path: seed.local.sql
